#ifndef TORQUE_CONFIG_H
#define TORQUE_CONFIG_H

#include "IO_Constants.h"


// TODO THESE DONT BELONG HERE OR DO THEY
#define MOTOR_FORWARDS 1
#define MOTOR_REVERSE 0

#define INVERTER_DISABLE 0
#define INVERTER_ENABLE 1

#define INVERTER_SPEED_ENABLE 1
#define INVERTER_SPEED_DISABLE 0

/* Drivetrain geometry (fixed). */
#define GEAR_RATIO 3.4545f
#define WHEEL_DIAMETER_DEFAULT 16

/* Default values for runtime-configurable parameters (EEPROM-backed). */
#define MAX_TORQUE_DEFAULT 100

#define PERCENT_TRAVEL_FOR_MAX_TORQUE 90

#define MOTOR_DIRECTION_DEFAULT MOTOR_FORWARDS // backwards for dyno testing

typedef enum {
	REGEN_STRATEGY_FRONT_ONLY = 0,
	REGEN_STRATEGY_REAR_ONLY,
	REGEN_STRATEGY_AVERAGED,
} RegenStrategy_t;

/* Regen defaults (runtime-configurable, EEPROM-backed). */
#define REGEN_ENABLED_DEFAULT TRUE
#define REGEN_MAX_TORQUE_DEFAULT 80
#define REGEN_MIN_TORQUE_DEFAULT 10
#define REGEN_MIN_BSE_REAR_PSI_DEFAULT 200
#define REGEN_MIN_BSE_FRONT_PSI_DEFAULT 200
#define REGEN_MAX_BSE_REAR_PSI_DEFAULT 500
#define REGEN_MAX_BSE_FRONT_PSI_DEFAULT 500
#define REGEN_MIN_SPEED_DEFAULT 500
#define REGEN_MAX_SOC_DEFAULT 85
#define REGEN_STRATEGY_DEFAULT REGEN_STRATEGY_AVERAGED

/* Traction control defaults (runtime-configurable, fractional values x1000). */
#define TRACTION_CONTROL_ENABLED_DEFAULT             FALSE
#define TRACTION_CONTROL_TARGET_SLIP_X1000_DEFAULT   1100
#define TRACTION_CONTROL_KP_X1000_DEFAULT            5000
#define TRACTION_CONTROL_KI_X1000_DEFAULT            0
#define TRACTION_CONTROL_KD_X1000_DEFAULT            0
#define TRACTION_CONTROL_MIN_FRONT_RPM_DEFAULT       10

#endif // TORQUE_CONFIG_H
