#ifndef DEBUG_DEFINES_H_INCLUDED
#define DEBUG_DEFINES_H_INCLUDED


#define IGNORE_RTD_SWITCH   FALSE

#define IGNORE_RTD_BRAKES   FALSE

#define IGNORE_APPS_ERRORS  FALSE
#define IGNORE_BSE_ERRORS   FALSE
#define IGNORE_SDC          FALSE

#define IGNORE_BRAKE_PLAUSIBILITY   FALSE

#define IGNORE_TSIL_TIMEOUT         FALSE

#endif
