#ifndef DEBUG_DEFINES_H
#define DEBUG_DEFINES_H

#include "IO_Constants.h"

#define IGNORE_RTD_SWITCH 0

#define IGNORE_RTD_BRAKES 1

#define IGNORE_APPS_ERRORS 0
#define IGNORE_BSE_ERRORS 1
#define IGNORE_SDC 0

#define IGNORE_BRAKE_PLAUSIBILITY 1

#define IGNORE_TSIL_TIMEOUT 0

#endif // DEBUG_DEFINES_H
