#ifndef DEBUG_DEFINES_H_INCLUDED
#define DEBUG_DEFINES_H_INCLUDED


// #define IGNORE_RTD_SWITCH

// #define IGNORE_RTD_BRAKES

// #define IGNORE_APPS_ERRORS
// #define IGNORE_BSE_ERRORS
// #define IGNORE_SDC

// #define IGNORE_BRAKE_PLAUSIBILITY

// #define IGNORE_TSIL_TIMEOUT

#endif
